# Generated by Django 5.0.6 on 2024-07-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colour',
            old_name='color',
            new_name='colour',
        ),
    ]
