# Generated by Django 5.0.6 on 2024-07-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_alter_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='colour',
            field=models.CharField(max_length=30),
        ),
    ]
