# Generated by Django 5.0.6 on 2024-07-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_alter_colour_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='waranty',
            new_name='warranty',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
