# Generated by Django 5.0.6 on 2024-07-05 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='profile',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='about.profile'),
        ),
    ]
