# Generated by Django 5.0.6 on 2024-07-06 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_order_status_last_updated_alter_cart_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='msg',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.profile'),
        ),
    ]
